# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ruby-codesign"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Emil Palm"]
  s.date = "2012-10-28"
  s.description = "TODO: longer description of your gem"
  s.email = "emil.palm@blocket.se"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ruby-codesign.rb",
    "lib/ruby-codesign/.DS_Store",
    "lib/ruby-codesign/helpers/.DS_Store",
    "lib/ruby-codesign/helpers/apple/base.rb",
    "lib/ruby-codesign/helpers/apple/provisioning_profiles.rb",
    "lib/ruby-codesign/helpers/base.rb",
    "lib/ruby-codesign/helpers/globber.rb",
    "lib/ruby-codesign/helpers/identity.rb",
    "lib/ruby-codesign/identity.rb",
    "lib/ruby-codesign/signer.rb",
    "test/helper.rb",
    "test/test_helpers_apple_provisioning_profiles.rb",
    "test/test_helpers_identity.rb",
    "test/test_ruby-codesign.rb"
  ]
  s.homepage = "http://github.com/mrevilme/ruby-codesign"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<grayhound>, [">= 0"])
      s.add_runtime_dependency(%q<CFPropertyList>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<grayhound>, [">= 0"])
      s.add_dependency(%q<CFPropertyList>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<grayhound>, [">= 0"])
    s.add_dependency(%q<CFPropertyList>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

